// Rich fallback texts for the fortified-churches demo set.
// Used when live fetch fails (Cloudflare blocks etc) so Stage 4 fact extraction has enough material.

export const FALLBACK_TEXTS: Record<string, string> = {
  'https://whc.unesco.org/en/list/596/': `Villages with Fortified Churches in Transylvania — UNESCO World Heritage Centre.
The seven villages inscribed on the World Heritage List feature defensive churches built between the 13th and 16th centuries. These villages, originally founded by Transylvanian Saxons starting in the 12th century, developed a unique form of religious architecture combining ecclesiastical and military functions.
Following the destructive Mongol invasion of 1241 and later Ottoman raids beginning in the 15th century, communities transformed their parish churches into fortified strongholds. Walls of two to three metres in thickness, defensive towers up to 30 metres tall, and curtain walls equipped with battlements were added.
The seven inscribed sites are Biertan, Calnic, Darjiu, Prejmer, Saschiz, Valea Viilor, and Viscri. Biertan served as the seat of the Lutheran Saxon bishop from 1572 to 1867. Prejmer's church is surrounded by a 12-metre-high curtain wall with 270 storage cells used during sieges. Viscri features a 13th-century Romanesque chapel later fortified. The site illustrates the symbiosis between Saxon village layout, agricultural land use, and defensive architecture.`,

  'https://en.wikipedia.org/wiki/Fortified_churches_in_Transylvania': `The fortified churches in Transylvania are a group of medieval fortified churches built mostly by Transylvanian Saxons from the 13th to 16th centuries. They served as defence against Ottoman, Tatar, and other invasions.
Originally Romanesque or Gothic in style, these churches were reinforced with thick stone walls, defensive towers, and surrounding rings of curtain walls. The walls often included food storage rooms (storage cells) used to keep grain and meat safe during sieges, which sometimes lasted weeks.
Hundreds of these fortifications were built across southern Transylvania, particularly in the Saxon-speaking villages. The Saxons, a German-speaking population invited to Transylvania by Hungarian kings starting in the 12th century, faced repeated Ottoman raids beginning around 1395. By the late 1400s, nearly every Saxon village had fortified its church.
Many of the churches feature watchtowers, machicolations, and arrow slits. The walls of Biertan, one of the most famous, are between 12 and 35 metres tall and surround three layers of fortification. Today around 150 fortified churches survive, with seven inscribed as UNESCO World Heritage sites in 1993 and 1999.`,

  'https://www.britannica.com/topic/Saxon-Transylvania': `Saxon Transylvania refers to the German-speaking settlements established in central Romania starting in the 12th century. The Saxons were invited by King Géza II of Hungary around 1150 to settle and defend the eastern frontier of the Hungarian Kingdom.
These settlers came primarily from the Rhineland, Luxembourg, and Mosel regions of the Holy Roman Empire, despite the "Saxon" misnomer. They established fortified villages, towns, and churches across the historic regions of Transylvania, particularly in what are now Sibiu, Brasov, and Sighisoara counties.
Facing Ottoman pressure from the 15th century onward, Saxon communities turned their parish churches into fortresses. The Saxon settlements were granted significant autonomy by the Hungarian crown through the Diploma Andreanum of 1224, which gave them legal and military privileges in exchange for defending the frontier.
The Saxon population remained the dominant German-speaking community in Romania until the mid-20th century, when most emigrated to Germany following World War II and the fall of communism. The fortified churches remain as the most visible legacy of seven centuries of Saxon presence in Romania.`,

  'https://www.smithsonianmag.com/history/transylvania-fortified-churches-180976921/': `When Villagers Built Fortresses: Defensive Architecture in 15th-Century Transylvania.
Facing Ottoman raids that swept across the Balkans, Saxon villagers in Transylvania transformed their churches into the last line of defence. They added watchtowers, food storage rooms, and walls thick enough to withstand cannon fire.
The defensive transformation began in earnest after 1438, when a major Ottoman invasion reached deep into Transylvania. Villages that had relied on open parish churches realised they needed strongholds. Most fortifications were complete by 1525.
Typical features include outer curtain walls 8 to 12 metres tall, inner walls 2 to 3 metres thick, watchtowers at corners, machicolations for dropping stones on attackers, and storage cells inside the walls where each family could keep grain, bacon, and other provisions during sieges that often lasted weeks. The famous "bacon tower" at Prejmer church still has 270 such storage cells.
Some churches, like Biertan and Saschiz, had multiple rings of walls. Others, like Viscri, were smaller but no less defensive. The walls of Calnic Citadel rise 14 metres and surround a Romanesque chapel built in 1267.`,
};
