import jsPDF from 'jspdf';

type ExportData = {
  display_name: string;
  mission: { title: string; topic: string };
  refined_query: string | null;
  badges: string[];
  sources: Array<{ url: string; title: string; domain: string }>;
  facts: Array<{ fact: string; explanation?: string; grade?: string }>;
  hallucination_score?: { correct: number; total: number };
  source_score?: { agree: number; total: number };
};

export function generatePDF(data: ExportData): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 50;
  const pageW = doc.internal.pageSize.getWidth();
  const maxW = pageW - margin * 2;
  let y = margin;

  function line(text: string, opts: { size?: number; bold?: boolean; color?: [number, number, number] } = {}) {
    doc.setFont('helvetica', opts.bold ? 'bold' : 'normal');
    doc.setFontSize(opts.size || 11);
    if (opts.color) doc.setTextColor(...opts.color);
    else doc.setTextColor(20, 20, 20);
    const split = doc.splitTextToSize(text, maxW);
    for (const ln of split) {
      if (y > 800) {
        doc.addPage();
        y = margin;
      }
      doc.text(ln, margin, y);
      y += (opts.size || 11) * 1.25;
    }
  }
  function gap(n = 8) {
    y += n;
  }
  function hr() {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageW - margin, y);
    gap(12);
  }

  line('SLEUTH RESEARCH BRIEF', { size: 9, color: [200, 130, 0] });
  line(data.mission.title, { size: 22, bold: true });
  line(`by ${data.display_name}`, { size: 11, color: [100, 100, 100] });
  gap(6);
  hr();

  line('RESEARCH QUESTION', { size: 9, color: [200, 130, 0], bold: true });
  line(data.refined_query || data.mission.topic, { size: 13 });
  gap(10);

  if (data.badges.length) {
    line('BADGES EARNED', { size: 9, color: [200, 130, 0], bold: true });
    line(data.badges.map((b) => `* ${b}`).join('   '), { size: 11 });
    gap(10);
  }

  if (data.source_score || data.hallucination_score) {
    line('SCORES', { size: 9, color: [200, 130, 0], bold: true });
    if (data.source_score) line(`Source judgment: ${data.source_score.agree}/${data.source_score.total} agreed with coach`);
    if (data.hallucination_score)
      line(`Hallucination spotting: ${data.hallucination_score.correct}/${data.hallucination_score.total} correct`);
    gap(10);
  }

  hr();
  line('TRIANGULATED FACTS', { size: 9, color: [200, 130, 0], bold: true });
  gap(4);
  data.facts.forEach((f, i) => {
    line(`${i + 1}. ${f.fact}`, { size: 12, bold: true });
    if (f.explanation) {
      line(`In my own words: ${f.explanation}`, { size: 11 });
    }
    if (f.grade) {
      line(`(coach grade: ${f.grade})`, { size: 9, color: [120, 120, 120] });
    }
    gap(6);
  });

  gap(8);
  hr();
  line('SOURCES CITED', { size: 9, color: [200, 130, 0], bold: true });
  gap(4);
  data.sources.forEach((s, i) => {
    line(`[${i + 1}] ${s.title}`, { size: 11, bold: true });
    line(`    ${s.url}`, { size: 9, color: [80, 80, 200] });
    gap(4);
  });

  gap(10);
  hr();
  line('Generated by Sleuth — research with friction', { size: 9, color: [150, 150, 150] });

  const safeName = data.display_name.replace(/[^a-z0-9]/gi, '_');
  doc.save(`Sleuth-Research-Brief-${safeName}.pdf`);
}
